name: docker_build_push
description: Build and push Docker image to Docker Hub
inputs:
  DOCKER_LATEST_IMAGE_TAG:
    description: Docker image tag
    required: false
    default: 'latest-staging'
  DOCKER_IMAGE_TAG:
    description: Docker image tag
    required: true
  DOCKERHUB_ORGANISATION:
    description: Docker Hub organisation
    required: true
  DOCKERHUB_USERNAME:
    description: Docker Hub username
    required: true
  DOCKERHUB_PASSWORD:
    description: Docker Hub password
    required: true
runs:
  using: composite
  steps:
    - name: Building docker image 🐳
      env:
        DOCKERHUB_ORGANISATION: ${{ inputs.DOCKERHUB_ORGANISATION }}
        DOCKER_IMAGE_TAG: ${{ inputs.DOCKER_IMAGE_TAG }}
        DOCKER_LATEST_IMAGE_TAG: ${{ inputs.DOCKER_LATEST_IMAGE_TAG }}
      run: |
        docker build -t $DOCKERHUB_ORGANISATION/deriv-com-api:$DOCKER_IMAGE_TAG -t $DOCKERHUB_ORGANISATION/deriv-com-api:$DOCKER_LATEST_IMAGE_TAG .
      shell: bash

    - name: Verify nginx image
      env:
        DOCKERHUB_ORGANISATION: ${{ inputs.DOCKERHUB_ORGANISATION }}
        DOCKER_LATEST_IMAGE_TAG: ${{ inputs.DOCKER_LATEST_IMAGE_TAG }}
      run: |
        set -e
        docker run --rm $DOCKERHUB_ORGANISATION/deriv-com-api:$DOCKER_LATEST_IMAGE_TAG nginx -t
        echo "docker image validated successfully"
      shell: bash

    - name: Pushing Image to docker hub 🐳
      env:
        DOCKERHUB_ORGANISATION: ${{ inputs.DOCKERHUB_ORGANISATION }}
        DOCKER_IMAGE_TAG: ${{ inputs.DOCKER_IMAGE_TAG }}
        DOCKER_LATEST_IMAGE_TAG: ${{ inputs.DOCKER_LATEST_IMAGE_TAG }}
        DOCKERHUB_PASSWORD: ${{ inputs.DOCKERHUB_PASSWORD }}
        DOCKERHUB_USERNAME: ${{ inputs.DOCKERHUB_USERNAME }}
      run: |
        echo $DOCKERHUB_PASSWORD | docker login -u $DOCKERHUB_USERNAME --password-stdin
        docker push $DOCKERHUB_ORGANISATION/deriv-com-api:$DOCKER_IMAGE_TAG
        docker push $DOCKERHUB_ORGANISATION/deriv-com-api:$DOCKER_LATEST_IMAGE_TAG
      shell: bash
