name: versioning
description: Generates a version for the build
inputs:
  RELEASE_TYPE:
    description: Release Type
    required: false
    default: staging
  RELEASE_TAG:
    description: Release Tag
    required: true
runs:
  using: composite
  steps:
    - name: Tag build
      env:
        RELEASE_TYPE: ${{ inputs.RELEASE_TYPE }}
        RELEASE_TAG: ${{ inputs.RELEASE_TAG }}
      run: echo "$RELEASE_TAG" > build/version.txt
      shell: bash
