name: Deriv Api Docs Legacy Workflow
on:
  push:
    branches:
      - legacy
env:
  RELEASE_TYPE: Production
jobs:
  build_and_publish:
    name: Builds and Publishes to Cloudflare Pages Legacy
    environment: Production
    runs-on: ubuntu-latest
    permissions:
      contents: read
    outputs:
      RELEASE_VERSION: ${{ steps.extract_version.outputs.RELEASE_VERSION }}
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
      - name: Setup Node
        uses: ./.github/actions/setup_node
      - name: Install dependencies
        uses: ./.github/actions/npm_install_from_cache
      - name: Build
        uses: ./.github/actions/build
        with:
          NODE_ENV: production
          TRACKJS_TOKEN: ${{ secrets.TRACKJS_TOKEN }}
          RUDDERSTACK_KEY: ${{ vars.RUDDERSTACK_KEY }}
          GROWTHBOOK_CLIENT_KEY: ${{ vars.GROWTHBOOK_CLIENT_KEY }}
      - name: Versioning
        uses: ./.github/actions/versioning
        with:
          RELEASE_TAG: ${{ github.ref_name }}
          RELEASE_TYPE: ${{ env.RELEASE_TYPE }}
      - name: Extract version
        id: extract_version
        run: echo "RELEASE_VERSION=$(cat build/version.txt)" >> $GITHUB_OUTPUT
      - name: Publish to Cloudflare Pages Legacy
        uses: ./.github/actions/publish_to_pages_legacy
        with:
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
      - name: Upload Build Artifact
        uses: actions/upload-artifact@26f96dfa697d77e81fd5907df203aa23a56210a8
        with:
          name: build
          path: build
          retention-days: 1
